---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: whoami-cert
  namespace: whoami
spec:
  commonName: whoami.cert.k8s.rsletten.com
  secretName: whoami-cert
  dnsNames:
    - whoami.cert.k8s.rsletten.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: powpow-cert
  namespace: whoami
spec:
  commonName: powpow.cert.k8s.rsletten.com
  secretName: powpow-cert
  dnsNames:
    - powpow.cert.k8s.rsletten.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
